config/routes.rb
Rails.application.routes.draw do
  get :javascript, to: 'javascript/index#page'
  root to: 'home/index#page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home/index_controller.rb
class Home::IndexController < ApplicationController
  def page
    render locals: {
      page: home_index_page,
      ruby_on_rails: ruby_on_rails,
      rails_casts: rails_casts,
      rails_links: rails_links
    }
  end

  private

    def datasource
      @datasource ||= HomeDatasource.new
    end

    def home_index_page
      HomePage.new datasource.page_data
    end

    def ruby_on_rails
      @ruby_on_rails ||= Home::Index::RubyOnRailsOrgComponent.new
    end

    def rails_casts
      @rails_casts ||= Home::Index::RailsCastsComponent.new
    end

    def rails_links
      @rails_links ||= Home::Index::RailsLinksComponent.new datasource.rails_links
    end
end

app/controllers/javascript/index_controller.rb
class Javascript::IndexController < ApplicationController
  def page
    render locals: {
      page: javascript_index_page
    }
  end

  private

    def javascript_index_page
      JavascriptPage.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_html_title title
    "#{set_title title}Rails 5 Prototype"
  end

  def set_title title
    "#{title} | " if title.present?
  end
end

app/views/home/index.html.slim
.container
  h1.title = page.title
  h2.subtitle = page.subtitle

= render page.first_block_path,
  data: page.data.first_block,
  ruby_on_rails: ruby_on_rails

= render page.second_block_path,
  data: page.data.second_block,
  rails_casts: rails_casts

= render page.third_block_path,
  data: page.data.third_block,
  rails_links: rails_links

- content_for :title, page.title
- content_for :description, page.subtitle
- content_for :page_id, page.id

app/views/home/index/blocks/_first_block.html.slim
.container
  .content
    hr
    h4.title = data.title
    p This line is written directly in the first block file.
    p = data.description
    p
      | The button below is rendered via
      = ' '
      strong Home::Index::RubyOnRailsOrgComponent
      |  owned by
      = ' '
      strong Home#index
      |  controller.
    p = render ruby_on_rails.component_path, ruby_on_rails: ruby_on_rails

app/views/home/index/blocks/_fourth_block.html.slim
.container.js-fourth-block
  .content
    hr
    h4.js-title
    p.js-description

app/views/home/index/blocks/_second_block.html.slim
.container
  .content
    hr
    h4.title = data.title
    p This line is written directly in the second block file.
    p
      | The button below is rendered via
      = ' '
      strong Home::Index::RailsCastsComponent
      |  owned by
      = ' '
      strong Home#index
      |  controller by extending the
      = ' '
      strong Utilities::LinkButtonComponent
      | .
    p = render rails_casts.component_path, link_button: rails_casts

app/views/home/index/blocks/_third_block.html.slim
.container
  .content
    hr
    h4 = data.title
    p This line is written directly in the third block file.
    p
      | The buttons below are rendered via
      = ' '
      strong Home::Index::RailsLinksComponent
      |  owned by
      = ' '
      strong Home#index
      |  controller by instantiating the
      = ' '
      strong Utilities::LinkButtonComponent
      | .
    - rails_links.link_buttons.each do |link_button|
      p = render link_button.component_path, link_button: link_button

app/views/home/index/components/ruby_on_rails/_button.html.slim
= link_to ruby_on_rails.link, target: '_blank' do
  = button_tag ruby_on_rails.text, class: 'button is-primary'

app/views/home/index/page.html.slim
.container
  h1.title = page.title
  h2.subtitle = page.subtitle

= render page.first_block_path,
  data: page.data.first_block,
  ruby_on_rails: ruby_on_rails

= render page.second_block_path,
  data: page.data.second_block,
  rails_casts: rails_casts

= render page.third_block_path,
  data: page.data.third_block,
  rails_links: rails_links

= render page.fourth_block_path

- content_for :title, page.title
- content_for :description, page.subtitle
- content_for :page_id, page.id

- content_for :javascript_includes_after do
  = javascript_include_tag page.js_path
  javascript:
    document.addEventListener('DOMContentLoaded', function(){
      App.Pages.Home.init();
    });

app/views/javascript/index/blocks/_description.html.slim
.container
  .content
    hr
      p
        | Majority of the JavaScript codes are written using&nbsp;
        strong Vanilla JS
        | &nbsp;and only use&nbsp;
        strong jQuery
        | &nbsp;for complex functions such as&nbsp;
        strong $(selector).animate()
        | .

app/views/javascript/index/page.html.slim
.container
  h1.title = page.title
  h2.subtitle = page.subtitle

= render page.description_path

- content_for :title, page.title
- content_for :description, page.subtitle

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    title = set_html_title(yield :title)
    meta content='width=device-width, initial-scale=1' name='viewport'
    meta content="#{yield :description}" name='description'
    meta content='ie=edge' http-equiv='x-ua-compatible'
    = csrf_meta_tags
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = yield :javascript_includes_before
  body
    = render 'layouts/blocks/header'
    main.main-content role='main' id="#{yield :page_id}"
      noscript
        p JavaScript must be enabled to make this application works.
      = yield
    = render 'layouts/blocks/footer'
    = yield :javascript_includes_after

app/views/layouts/blocks/_footer.html.slim
footer.main-footer
  .container
    p.has-text-centered
      = link_to 'Rails 5 Prototype', ''
      | &nbsp;
      | &copy; July 2017

app/views/layouts/blocks/_header.html.slim
nav.navbar.main-navbar
  .navbar-brand
    = link_to '', class: 'navbar-brand-link' do
      strong Rails 5 Prototype
    .navbar-burger.burger data-target='mainNavMenu'
      span
      span
      span
  #mainNavMenu.navbar-menu
    .navbar-start
      = link_to 'Home', root_path, class: 'navbar-item'
      = link_to 'Hybrid JavaScript', javascript_path, class: 'navbar-item'